### ISSUE TITLE
error al insertar en tabla shelters

### ISSUE THREAD

**Issue by fabian-juarez** [juliobarreraa/sismomx-library#29]
Integrity constraint violation: 1048 Column 'location' cannot be null (SQL: insert into `sismomx_shelters` (`encoded_key`, `location`, `receiving`, `address`, `zone`, `map`, `more_information`, `updated_at`, `created_at`) values (2b32a261e5f517f73a73a0a5305a9cab8c29f144d15b2d612a6c24eaff90aefc, , , , , , , , 2017-09-26 21:40:04))

**Comment by fabian-juarez** [comment]
Integrity constraint violation: 1048 Column 'address' cannot be null (SQL: insert into `sismomx_shelters` (`encoded_key`, `location`, `receiving`, `address`, `zone`, `map`, `more_information`, `updated_at`, `created_at`) values (2b32a261e5f517f73a73a0a5305a9cab8c29f144d15b2d612a6c24eaff90aefc, , , , , , , , 2017-09-27 00:20:04))

**Comment by fejimene** [comment]
Supongo que sí aceptamos tener locations y addresses null? Puedo hacer un migration con estos campos nullables

**Comment by juliobarreraa** [comment]
Los idea es ya no aceptarlos para poder generar la normalización de la información, de todas manera vamos definir que datos son requeridos y cuáles no. En caso de ser requerido y no estar presente, se procederá a omitir el registro.
